version: '3.8'
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=algorizz
      - POSTGRES_PASSWORD=algorizz
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres: